Responsive account, update ui
NatiqQuran/nq-frontend pull request #36
Opened 2022-10-12 14:03 UTC by ekiuse

2022-10-12 20:09 UTC, nexnema requested changes

2022-10-12 20:09 UTC, nexnema commented on src/ui/gridContainer/gridContainer.module.css
>  .container {
change name to gridContainer

2022-10-12 20:09 UTC, nexnema commented on src/ui/header/header.module.css
>  .appBar {
change name

2022-10-12 20:09 UTC, nexnema commented on src/ui/header/header.tsx
> +function Header(props: React.HTMLAttributes<HTMLElement>) {
do we have <HTMLHeaderElement>?

2022-10-12 20:09 UTC, nexnema commented on src/ui/svgIcon/svgIcon.module.css
> +
add a task in project, to change SvgIcon entirely

2022-10-12 21:46 UTC, ekiuse commented on src/ui/header/header.tsx
> +function Header(props: React.HTMLAttributes<HTMLElement>) {
What should I change?

2022-10-12 22:45 UTC, nexnema commented on src/ui/header/header.tsx
> +function Header(props: React.HTMLAttributes<HTMLElement>) {
do we have HTMLHeaderElement?

2022-10-13 09:05 UTC, nexnema approved these changes

2022-10-13 10:37 UTC, merged