New Update
NatiqQuran/nq-frontend pull request #9
Opened 2022-09-22 12:58 UTC by AzerothA

2022-09-23 10:02 UTC, nexnema requested changes
Check comments, fix or explain them. thank you.

2022-09-23 10:02 UTC, nexnema commented on src/ui/page/page.module.css
> +    height: 100%;
don't use height 100%, never ever.

2022-09-23 10:02 UTC, nexnema commented on src/ui/theme/useTheme.tsx
> +function useTheme(styles: string) {
Explain me this function.

2022-09-23 10:02 UTC, nexnema commented on src/index.tsx
> +// import "./assets/css/color.css";
Why you comment this line?

2022-09-24 05:59 UTC, AzerothA commented on src/ui/button/button.tsx
> +        variantStyle,
Join the styles to a one string

2022-09-24 06:03 UTC, AzerothA commented on src/ui/theme/useTheme.tsx
> +function useTheme(styles: string) {
Adds a variables class to the HTML tag.
And uses the effect to do that.

Maybe we can use a better way.

2022-09-24 08:33 UTC, AzerothA commented on src/index.tsx
> +// import "./assets/css/color.css";
because it's not an efficient way to use Theme.

2022-09-24 11:04 UTC, nexnema commented on src/index.tsx
> +// import "./assets/css/color.css";
then, remove it.

2022-09-24 11:51 UTC, merged